### PR TITLE
Fix ripping when data track is the first track.

### LINKED ISSUE #174: Ensure that multi-sessions are still read correctly by whipper
@RecursiveForest reworked the cdrdao parsing logic, and I am kind of afraid that that broken multisession CDs. We need to double-check that this is not the case, or fix it.

### PR DESCRIPTION
**Pull request by Jormangeud**
This should fix #174.

### CODE REVIEW

**Comment by MerlijnWajer** [comment]
Thanks for this PR. Let me find a bit of time to review this. I think more is required; for example, accuraterip records might not also be accurately read. And some CDs have intermixed sessions of data tracks and audio tracks, so just this special case is not enough. I need to review my code and see how I did it. There are also CDs that are not even multisession but still have data and audio tracks in one session.

**Comment by Jormangeud** [comment]
I moved this to a branch, but I'm not sure if it is possible to update it to this.
https://github.com/Jormangeud/whipper/tree/fix-1st-track-is-data-track

**Comment by JoeLametta** [comment]
@MerlijnWajer Ping.

/remind MerlijnWajer "try to review this pull request" in a week

**Comment by JoeLametta** [comment]
> I moved this to a branch, but I'm not sure if it is possible to update it to this.

???

**Comment by MerlijnWajer** [comment]
@Jormangeud - opening a new pull request probably makes sense.
Looking at this commit: https://github.com/Jormangeud/whipper/commit/d6d4c84567491a240f76f0234c384158868d5fc1 I think it would make more sense to fix it in a more generic manner, that is, there may be CDs with several sessions, with data and audio intermixed. Not just data at the start. Ideally, we'd make it work for this too.

**Comment by MerlijnWajer** [comment]
This is not code you can copy/paste or use-as-is (it won't work), but I used something like this a while ago. Note that this code doesn't rip all the data tracks if there are multiple separate sessions (I haven't figured out an easy, but it's also out of scope of this issue):

```    def rip_tracks(self):
        self.rs.profile = self.ripper.setup_things()

        # TODO: rip impl
        self.rs.htoapath = self.ripper.rip_htoa(self.rs.profile,
                                                self.rs.disambiguate)

        self.data_tracks_ripped = False

        for i, track in enumerate(self.ripper.itable.tracks):
            logger.debug(u'Ripping track: %d %s', i, track)
            if not track.audio:
                if self.data_tracks_ripped:
                    logging.debug(u'Not ripping data tracks again, already'
                                  ' ripped once')

                else:
                    self.rip_data_track()
                    self.data_tracks_ripped = True

                track.indexes[1].relative = 0
            else:
                audio_tracks_left = filter(lambda x: x.audio,
                                           self.ripper.itable.tracks[i:])

                # is_last is only used to control the speed of the rip when we're doing fast rips - to use -Y at the last track instead of -Z
                is_last = len(audio_tracks_left) == 1

                self.rip_audio_track(i, last=is_last)

                ## Previous a data track?
                if i > 0 and not self.ripper.itable.tracks[i-1].audio:
                    if track.getPregap() > 0:
                        index = track.getFirstIndex()
                        index.relative = 0


            self.progress['total_progress'] = \
                    float(i + 1) / len(self.ripper.itable.tracks)
            self.report()

            if self.skip_fast_mode_oracle():
                self._allow_fast_rip = False

```

**Comment by MerlijnWajer** [comment]
Additionally, the accuraterip checksum results also do not 'count' the data tracks in the middle or at the start, so you need to correct for those too (in the index) when comparing accurate rip checksums of audio tracks.

**Comment by MerlijnWajer** [comment]
@JoeLametta how do you suggest we save the info above - because the PR is already closed. Migrate it to some issue?

**Comment by JoeLametta** [comment]
> @JoeLametta how do you suggest we save the info above - because the PR is already closed. Migrate it to some issue?

Done in https://github.com/whipper-team/whipper/issues/174#issuecomment-442801772 :wink:

**Pull request closed without merging**
