### PR TITLE
Update accuraterip-checksum

### PR DESCRIPTION
**Pull request by Freso**
[Version 1.5](https://github.com/leo-bogert/accuraterip-checksum/releases/tag/version1.5) was released back in June and has a fix to work on 32-bit platforms (contributed by @MerlijnWajer).

### CODE REVIEW

**Comment by MerlijnWajer** [comment]
Looks good to me (once all checks pass)

**Comment by JoeLametta** [comment]
Thanks for the pull request!

@Freso should we update [this section](https://github.com/whipper-team/whipper#building-the-bundled-dependencies) of the README? (and/or add it to the list of [required dependencies](https://github.com/whipper-team/whipper#required-dependencies)? - in case the right version is already packaged)

**Comment by Freso** [comment]
> should we update [this section](https://github.com/whipper-team/whipper#building-the-bundled-dependencies) of the README?

I didn't update the `Makefile` to be the one from upstream (only the `.c` and `README.md` files), so there are no changes to those instructions AFAIK. (The `.travis.yml` works fine without alterations anyway.)

If it needs to be listed in dependencies or not is a question outside the scope of this PR I think, and I have no strong opinion either way currently. :)

**Comment by JoeLametta** [comment]
Merged, thanks!

**Pull request merged**
