### PR TITLE
Add man pages.

### PR DESCRIPTION
**Pull request by baldurmen**
Here we go!

This should make #446 obsolete :)

Once the man pages are built, you can view them locally with:

    man ./whipper.1

### CODE REVIEW

**Comment by baldurmen** [comment]
Well, Travis fails on py 3.5 and the Gtihub greeting script too? 90% sure those aren't my fault :p

**Comment by MerlijnWajer** [comment]
The worlds needs more restructured text. Thanks for picking this up.

**Comment by JoeLametta** [comment]
> Well, Travis fails on py 3.5 and the Gtihub greeting script too? 90% sure those aren't my fault :p

You're right, thanks for the pull request!

> Gtihub greeting script too

Unfortunately this is a known issue, unrelated to your pull request: https://github.com/actions/first-interaction/issues/10

> Well, Travis fails on py 3.5

Actually that is our CI job which checks for code issues (errors, PEP-8, etc.) using flake8. The issues reported here are real but unrelated to your pull request (it seems that the tool got updated and caught new issues).

The errors should now be fixed in `develop` (commit 752162a434db0b4ef3a83f04d6da1456a05e70b4).

**Comment by jwflory** [comment]
Hey @mruszczyk, it would be awesome to get these included in the Fedora RPM packages downstream for next release :smile: Btw thanks for packaging in Fedora!

**Comment by JoeLametta** [comment]
I still need to review and test this but it looks good. One little change I would like to see is adding a mention about the new dependency (docutils) to the README (optional dependencies section, I think) and a link to `man/README.md`. :wink: 

I may even add a new Travis CI job to detect future syntactic warnings/errors in the documentation files... Something like this should suffice:

```bash
for manpage in *.rst; do rst2man --exit-status=1 --report=1 --debug ${manpage} "${manpage%%.*}".1 ; done
```

**Comment by baldurmen** [comment]
@JoeLametta I'll let you play with Travis, as I have more experience with Gitlab CI. Fixed the other 2 things though.

**Comment by JoeLametta** [comment]
Will leave the Travis CI thing out of this.

**Comment by JoeLametta** [comment]
Merged, thanks!

**Pull request merged**
