### PR TITLE
Restore the ability to use inline comments in config files

### PR DESCRIPTION
**Pull request by neilmayhew**
This change is [Reviewable](https://reviewable.io/reviews/whipper-team/whipper/461)

### CODE REVIEW

**Comment by JoeLametta** [comment]
Hi, one clarification: you titled "restore" but when did we drop the ability to use inline commits? (in which commit?).

**Comment by neilmayhew** [comment]
I added more info in the commit message, and also updated [README.md](README.md). The exact commit where the ability was lost was 64dd9d843ab508651863fa30c73ab10a5b1e97f5 but I'm not sure this is important to include in the commit message.

**Comment by JoeLametta** [comment]
Um, [here](https://docs.python.org/2/library/configparser.html#ConfigParser.SafeConfigParser) I see this:
> (For backwards compatibility, only `;` starts an inline comment, while `#` does not.)

Also keep in mind that inline comments may cause interpolation errors. Example here: https://github.com/whipper-team/whipper/issues/443#issuecomment-570795143.

Don't know if restoring this would be a good idea...

**Comment by neilmayhew** [comment]
I suspect that #443 is actually a result of the problem this PR is trying to fix, because the comments won't have been treated as comments in any Python 3 version of whipper: they'll just have been part of the value. In other words, re-enabling inline comments would prevent that problem.

Without this PR, inline comments won't be possible at all, but they're used liberally in whipper's documentation and examples, so those places would all need to be updated.

However, more importantly, I expect many people (like me) have existing config files with comments in them that were used with a Python 2 version of whipper, and now whipper dies with a strange error message about boolean values whenever they try to run it.

**Comment by neilmayhew** [comment]
I'm not sure what you meant by the quote from the Python 2 documentation. That if we do re-enable comments we should allow only `;` and not `#`?

**Comment by JoeLametta** [comment]
Hi, after some tests I've verified that:
1. before the Python 3 port occurred whipper used to recognize inline comments starting with character `;` but not the ones with character `#`. This seems to be confirmed [here](https://docs.python.org/3.5/library/configparser.html#customizing-parser-behaviour) too †.
2. right now whipper allows no inline comments

I agree this is a regression so I'm going to merge this pull request but first I need you to edit it to remove character `#` as allowed inline comment prefix.

Cheers,
Joe

†
> *Changed in version 3.2:* In previous versions of [configparser](https://docs.python.org/3.5/library/configparser.html#module-configparser) behaviour matched
`comment_prefixes=('#',';')` and `inline_comment_prefixes=(';',)`.

**Comment by neilmayhew** [comment]
Yes, I agree it's best to match the original behaviour exactly. Done.

**Comment by JoeLametta** [comment]
Merged, thanks!

**Pull request merged**
