### PR TITLE
Various enhancements to our Travis CI setup

### PR DESCRIPTION
**Pull request by Freso**
See individual commit messages for explanations and rationale.

### CODE REVIEW

**Comment by JoeLametta** [comment]
It seems that we can [make Travis CI use xenial as a base](https://docs.travis-ci.com/user/reference/xenial/). I think that should satisfy  the enough recent `libgirepository-1.0` dependency. Am I missing something?

**Comment by Freso** [comment]
Well, depends on how old software has to be before we stop wanting to support it. :)

**Comment by JoeLametta** [comment]
> Well, depends on how old software has to be before we stop wanting to support it. :)

I think that's fine (it supports Xenial - Ubuntu's previous LTS, current Debian stable, Fedora, etc.) :wink:

**Comment by JoeLametta** [comment]
> It seems that we can [make Travis CI use xenial as a base](https://docs.travis-ci.com/user/reference/xenial/).

Yeah, let's do it.

**Comment by JoeLametta** [comment]
Done! (https://github.com/whipper-team/whipper/commit/bb6a29c5dfc0c945dcf39d6557bef3c37e797374)

**Pull request closed without merging**
