### PR TITLE
Add drive option to force using fast TOC

### PR DESCRIPTION
**Pull request by mtdcr**
This makes whipper compatible with my best drives, `MATSHITA DVD-RAM UJ-842 RB01` and
`MATSHITA DVD-R UJ-857E ZA0E`. I don't think there's a good way to autodetect the need for this option, since sometimes the drives wouldn't fail (the longer the disc's playing time, the more likely problems are to occur).

For further details on this topic see the discussion at PR https://github.com/JoeLametta/whipper/pull/264.

### CODE REVIEW

**Comment by JoeLametta** [comment]
I've edited and committed "config: generalize getting and setting of drive options" to `develop` in commit afc31f930e70729ba6709521cf0ca20f1c9828c8.

@Freso @MerlijnWajer are we interested in adding this to whipper?

**Comment by MerlijnWajer** [comment]
I unconditionally only use fast-toc for my work, so I'm fine with it.

**Comment by JoeLametta** [comment]
> I unconditionally only use fast-toc for my work, so I'm fine with it.

I think that if we decide to add support for a fast-toc mode we should report this in the log too.

**Comment by mtdcr** [comment]
I'm currently not planning to pursue this PR anymore, which is why I'm closing it. Feel free to take and modify these commits as you see fit!

**Pull request closed without merging**
