### PR TITLE
Change IRC pointers to point to Libera.Chat

### LINKED ISSUE #540: Switch official IRC channel off of freenode
freenode has experienced a hostile takeover. Pretty much all staff has resigned and the hardware freenode is using was on agreements with individual staffers, so no telling if freenode will even continue to function for much longer. https://gist.github.com/joepie91/df80d8d36cd9d1bde46ba018af497409 has some information on it.

Most freenode staff has moved to found [Libera.Chat](https://libera.chat/) and I would suggest we move the official `#whipper` channel to there as well.

(I have already registered the channel on LC, so it’s safe if we decide to do so.)

Please react to this issue with a :+1: if you are for moving over to Libera.Chat and :-1: if you are against. Questions and discussion in comments. :)

### PR DESCRIPTION
**Pull request by Freso**
AFAIK, there is no Matrix bridge yet(?), so removing the Matrix bit for now. Can be added back in later if/when a bridge is established.

Resolves https://github.com/whipper-team/whipper/issues/540

### CODE REVIEW

**Comment by Freso** [comment]
Build errors seem to be a PyPI/`pip` thing… I also don’t see how changing `README.md` would result in `whipper` no longer working. :|

**Comment by JoeLametta** [comment]
> Build errors seem to be a PyPI/`pip` thing… I also don’t see how changing `README.md` would result in `whipper` no longer working. :|

The errors manifested themselves because this branch was 88 commits behind develop (so the relevant fixes were missing):

travis_ci_failures_explanation

I've now rebased on `develop` and Travis CI stopped complaining :wink:

**Comment by Freso** [comment]
Oh. :joy: I’m going to re-rebase and force push. :see_no_evil:

**Comment by JuniorJPDJ** [comment]
If you can wait a bit - matrix bridge is comming: https://github.com/matrix-org/matrix-appservice-irc/issues/208

**Comment by Freso** [comment]
I’ll probably merge this later today, but we won’t shut off the current room until Matrix bridge (and maybe .onion service) is available. The README can easily be updated once bridge is up afterwards.

**Pull request merged**
