### PR TITLE
Replace sys.std{out,err} statements with logger/print calls

### LINKED ISSUE #303: use standard logging
whipper currently writes its error messages and output all jumbled up together on stdout, through the `Program._stdout` file handler. This is useful because it could allow some tests to parse the output of the program and verify things are working okay. That is not currently being used however, so it's unclear to me why this construct is present at all - the only test I could find that would use something like this `TestAccurateRipReport` and it directly hijacks `sys.stdout` and does not touch directly the `Program._stdout` handler.

So I would recommend switching to using the [logging](https://docs.python.org/3/library/logging.html) module. It's standard, well known and expected in Python programs. As a bonus, all messages will be written on stderr (as they should). logfile, syslog and other handlers support becomes trivial to implement as well. The conversion should be easy: just change:

    self._stdout.write("foo %s\n", bar)

to:

    logging.info("foo %s", bar)

or:

    logging.warning....

Depending on the severity level.

How does that sound?

### PR DESCRIPTION
**Pull request by JoeLametta**
Fixes #303.

### CODE REVIEW

**Comment by MerlijnWajer** [comment]
I would personally be in favour of using `logging` where you are currently using `print()` calls. Just turn them into debug level logging calls, or higher, if it makes sense.

**Comment by JoeLametta** [comment]
> I would personally be in favour of using `logging` where you are currently using `print()` calls. Just turn them into debug level logging calls, or higher, if it makes sense.

Even things like these?

```python
print('\nPicked requested release id %s' % release)
print('Artist: %s' % metadatas[0].artist.encode('utf-8'))
print('Title : %s' % metadatas[0].title.encode('utf-8'))
```

**Comment by JoeLametta** [comment]
I think it is complete now...

**Comment by MerlijnWajer** [comment]
Looks good to me.

**Pull request merged**
