### PR TITLE
WIP: Add manpage

### LINKED ISSUE #73: add manpage
What form this takes needs to come after we remove python-command.

### PR DESCRIPTION
**Pull request by JoeLametta**
This manpage is based on morituri's one (Debian version).
See: https://manpages.debian.org/jessie/morituri/rip.1

This is still WIP.

Fixes #73.

### CODE REVIEW

**Comment by JoeLametta** [comment]
@MerlijnWajer @Freso what's your opinion about this: is it garbage or good as a starting point?

**Comment by MerlijnWajer** [comment]
I'd personally write one in restructuredtext and use rst2man to generate one.

**Comment by JoeLametta** [comment]
> I'd personally write one in restructuredtext and use rst2man to generate one.

OK, do you have a draft ready?

**Comment by baldurmen** [comment]
I'm happy to take over this PR and use `rst2man`, as I've used it in the past for other projects using cli clients with sub-commands :)

**Comment by JoeLametta** [comment]
@baldurmen Thanks for the effort: it is surely appreciated!

**Comment by JoeLametta** [comment]
Closed because of #490.

**Pull request closed without merging**
